GET http://localhost:4000/flights
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjkzY2RhYTJmLWQ5MDItNDdlOC1hN2Q0LTRiMGI2ZmM0MDQ5NCIsIk5hbWUiOiJoZWxsbyIsIkVtYWlsIjoiaGVsbG9AZ21haWwuY29tIiwiUm9sZSI6InVzZXIiLCJpc1NlbnQiOiIwIiwiaWF0IjoxNjc3NTAzMzU3LCJleHAiOjE2Nzc1MDY5NTd9.wKRBeY3yScs9_iwxvJkv6DvOYBMNjNSNMaDWZcdnuhY
###
GET http://localhost:4000/flights/93067214-6361-4a02-ac1f-db118e6aa725
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjkzY2RhYTJmLWQ5MDItNDdlOC1hN2Q0LTRiMGI2ZmM0MDQ5NCIsIk5hbWUiOiJoZWxsbyIsIkVtYWlsIjoiaGVsbG9AZ21haWwuY29tIiwiUm9sZSI6InVzZXIiLCJpc1NlbnQiOiIwIiwiaWF0IjoxNjc3NTAzMzU3LCJleHAiOjE2Nzc1MDY5NTd9.wKRBeY3yScs9_iwxvJkv6DvOYBMNjNSNMaDWZcdnuhY
###
GET http://localhost:4000/flights/booking/emails
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImEwYTkxNWZjLWI5MjctNDZjMC1hZTcxLTgyNjMwMGU5OWQyMyIsIk5hbWUiOiJLdWt1IEFsaSBOZ29jaG8iLCJFbWFpbCI6IndyaWdodGt1a3UxMEBnbWFpbC5jb20iLCJSb2xlIjoidXNlciIsImlzU2VudCI6IjAiLCJpYXQiOjE2Nzc1NzA0MTUsImV4cCI6MTY3NzU3NDAxNX0.vbXO9iaR7EuVGxSGJ3dWWSL3C87vHyMt8Cvj9D7obN4
###
POST  http://localhost:4000/flights
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImEwYTkxNWZjLWI5MjctNDZjMC1hZTcxLTgyNjMwMGU5OWQyMyIsIk5hbWUiOiJLdWt1IEFsaSBOZ29jaG8iLCJFbWFpbCI6IndyaWdodGt1a3UxMEBnbWFpbC5jb20iLCJSb2xlIjoidXNlciIsImlzU2VudCI6IjAiLCJpYXQiOjE2Nzc1NzA0MTUsImV4cCI6MTY3NzU3NDAxNX0.vbXO9iaR7EuVGxSGJ3dWWSL3C87vHyMt8Cvj9D7obN4

{
    "Destination":"China",
    "TravelDate":"2023/03/03"
}

###
PUT  http://localhost:4000/flights/93067214-6361-4a02-ac1f-db118e6aa725
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjkzY2RhYTJmLWQ5MDItNDdlOC1hN2Q0LTRiMGI2ZmM0MDQ5NCIsIk5hbWUiOiJoZWxsbyIsIkVtYWlsIjoiaGVsbG9AZ21haWwuY29tIiwiUm9sZSI6InVzZXIiLCJpc1NlbnQiOiIwIiwiaWF0IjoxNjc3NTAzMzU3LCJleHAiOjE2Nzc1MDY5NTd9.wKRBeY3yScs9_iwxvJkv6DvOYBMNjNSNMaDWZcdnuhY
Content-Type: application/json

{
    
    "Destination":"Japan",
    "TravelDate":"2023/02/20"
}

###
GET http://localhost:4000/flights/c508e135-2cac-4a6f-bf49-0323db54bded


###
DELETE  http://localhost:4000/flights/c508e135-2cac-4a6f-bf49-0323db54bded



###
POST  http://localhost:4000/auth/register
Content-Type: application/json

{
    "Name":"Kuku Ali Ngocho",
    "Email":"wrightkuku10@gmail.com",
    "Password":"Tryme!here23"
}

###
POST  http://localhost:4000/auth/login
Content-Type: application/json

{
     "Email":"wrightkuku10@gmail.com",
    "Password":"Tryme!here23"
}


###
GET  http://localhost:4000/auth/home
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjkwOWMyNDhiLTMzYWItNDM5ZS04MTEyLTc2MDRmNzIwYjAyYiIsIk5hbWUiOiJFbHZpcyBHaXNpb3JhIiwiRW1haWwiOiJlbHZpc0BnbWFpbC5jb20iLCJSb2xlIjoidXNlciIsImlhdCI6MTY3NTg1MDY4OSwiZXhwIjoxNjc1ODU0Mjg5fQ.bPTAoivR1oa-ew0FqFHBhkccVTDI2P23yneLIxiBNNU